import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import MainHeader from "@/components/MainHeader";
import Container from "@/components/Container";
import { ThemeProvider } from "@/components/theming/ThemeProvider";
import { ThemeSwitcher } from "@/components/theming/ThemeSwitcher";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Logo: React.FC = () => (
  <>
    <Image
      className="hidden [.dark_&]:block"
      src="/brand/ZippyStarter/Logo/dark.svg"
      width={136}
      height={54}
      alt="ZippyStarter logo"
    />
    <Image
      className="[.dark_&]:hidden"
      src="/brand/ZippyStarter/Logo/light.svg"
      width={136}
      height={54}
      alt="ZippyStarter logo"
    />
  </>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          "grid gap-y-[clamp(4rem,16cqw,6.5rem)] grid-rows-[auto,1fr,auto] h-[100vh]",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Container component="header">
            <Container.Inner className="grid grid-cols-[1fr_auto]">
              <MainHeader href="/" logo={<Logo />} />
            </Container.Inner>
          </Container>
          <Container>
            <Container.Inner>{children}</Container.Inner>
          </Container>
          <Container component="footer">
            <Container.Inner className="grid grid-cols-[1fr_auto]">
              <div className="min-h-14"></div>
            </Container.Inner>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
